version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install -g serverless
  pre_build:
    commands:
      - echo '[*] Installing dependencies'
      - cd ${CODEBUILD_SRC_DIR}/api
      - npm install -q
  build:
    commands:
      - echo Build started on `date`
      - cd ${CODEBUILD_SRC_DIR}/api
      # Build.
      - npm run pack
  post_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/api
      - printenv
      - npm run deploy
artifacts:
  files:
    - '.serverless/**/*'
  name: api-artifacts
  discard-paths: no
  base-directory: ${CODEBUILD_SRC_DIR}/api
